help: 
	@echo "Usage:"
	@echo "make help: show help menu"
	@echo "make all: compile q6.c, q7.c as executable file sol_q6, sol_q7"
	@echo "make clean: remove object files"
	@echo "please enter ./sol_q6 or ./sol_q7 to test each result"
all:
	@ gcc -o ./sol_q6 ./q6/q6.c
	@ gcc -o ./sol_q7 ./q7/q7.c
clean:
	rm sol_q6 sol_q7
